org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.java.home=C:\\Program Files\\Java\\jdk-21.0.12
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false

# Reverting to default daemon strategy with optimized memory
kotlin.daemon.jvm.options=-Xmx1G
kotlin.compiler.execution.strategy=in-process
